### PR TITLE
feat(screenshare): electron desktop picker

### PR DESCRIPTION
**Pull request by virtuacoplenny**

### CODE REVIEW

**Comment by paweldomas** [comment]
This looks good to me

**Comment by virtuacoplenny** [comment]
Screenshots for reference. The designs are placeholder, though.
home_window
home_screen
call_window

**Comment by paweldomas** [comment]
Comment on the screenshots: maybe it would look better not transparent ?

**Comment by virtuacoplenny** [comment]
> Comment on the screenshots: maybe it would look better not transparent ?

Which part? The background behind the modal aka "shroud"?

**Comment by paweldomas** [comment]
It's just that you can see through it the other text: `How would you like to screenshare?`

**Comment by virtuacoplenny** [comment]
For reference, after the ui tweaks pawel wants:
Screen Shot 2019-03-19 at 6 24 29 PM

**Pull request merged**
